FROM psmware/devops-base
LABEL name="Pat's Ansible - PostgreSQL - REST API - POC"
LABEL vendor="psmware ltd"
LABEL com.sap.mclean.patrick.version="1.0"
LABEL com.sap.mclean.patrick.version.release-date="2020-04-10"
LABEL com.sap.mclean.patrick.version.version.is-production=""
